version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lerner-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3308xcgevi04"
s3_prefix = "lerner-bot"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
